### Get all appointments
GET http://localhost:8000/appointments
Accept: application/json
Cookie: {{auth_token}}

### Create a new appointment
POST http://localhost:8000/appointments
Content-Type: application/json
Accept: application/json
Cookie: {{auth_token}}
X-XSRF-TOKEN: {{auth_token}}

{
    "title": "Meeting with Team",
    "description": "Discuss project roadmap",
    "location": "Conference Room A",
    "start_time": "2023-10-27 10:00:00",
    "end_time": "2023-10-27 11:00:00"
}

### Update an appointment (Replace ID with a real ID)
PUT http://localhost:8000/appointments/1
Content-Type: application/json
Accept: application/json
Cookie: {{auth_token}}
X-XSRF-TOKEN: {{auth_token}}

{
    "title": "Updated Meeting Title",
    "description": "Updated description",
    "location": "Online",
    "start_time": "2023-10-28 14:00:00",
    "end_time": "2023-10-28 15:00:00"
}

### Delete an appointment (Replace ID with a real ID)
DELETE http://localhost:8000/appointments/1
Accept: application/json
Cookie: {{auth_token}}
X-XSRF-TOKEN: {{auth_token}}
