### Login and get CSRF token
POST http://localhost:8000/login
Content-Type: application/json
Accept: application/json

{
    "email": "test@test",
    "password": "12345678"
}

> {%
    client.global.set("auth_token", response.headers.valueOf("Set-Cookie"));
%}

### Logout
POST http://localhost:8000/logout
Accept: application/json
Cookie: {{auth_token}}
X-XSRF-TOKEN: {{auth_token}}

### Register
POST http://localhost:8000/register
Content-Type: application/json
Accept: application/json

{
    "name": "New User",
    "email": "newuser@example.com",
    "password": "password",
    "password_confirmation": "password"
}
