### Create Professional Area
POST http://localhost:8000/admin/professional-area
Content-Type: application/json
Accept: application/json
Cookie: {{auth_token}}
X-XSRF-TOKEN: {{auth_token}}

{
    "name": "Informatik"
}

### Update Professional Area (Replace ID with a real ID)
PUT http://localhost:8000/admin/professional-area/1
Content-Type: application/json
Accept: application/json
Cookie: {{auth_token}}
X-XSRF-TOKEN: {{auth_token}}

{
    "name": "Wirtschaftsinformatik"
}

### Delete Professional Area (Replace ID with a real ID)
DELETE http://localhost:8000/admin/professional-area/1
Accept: application/json
Cookie: {{auth_token}}
X-XSRF-TOKEN: {{auth_token}}

### Add Teacher to Area (Replace IDs with real IDs)
POST http://localhost:8000/admin/teacher-to-area/1/1
Accept: application/json
Cookie: {{auth_token}}
X-XSRF-TOKEN: {{auth_token}}

### Remove Teacher from Area (Replace IDs with real IDs)
DELETE http://localhost:8000/admin/teacher-to-area/1/1
Accept: application/json
Cookie: {{auth_token}}
X-XSRF-TOKEN: {{auth_token}}
